### ISSUE TITLE
Clicking Play Button

### ISSUE THREAD

**Issue by shirin-muataz-M** [kodo-yousif/hangman_react_js#7]
Everytime the user clicks on one of the letters the following should happen:
* The random word is search through to find if it contains the clicked letter, if the clicked letter is part of the random word's letters then it gets shown up instead of the space, if not, then the lives counter is decreased by one. In some rare cases a clicked letter corresponds to two letters in the generated word, if that happens then show both words.
* The button becomes disabled and should only work once.

**Comment by kodo-yousif** [comment]
it has been done on branches (kodo , Ravyar1 ) soon will be on branch master also.
